version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.dev
    image: auth-service:dev
    ports:
      - "8123:8000"
    env_file:
      - ./app/.env.dev
    environment:
      - PYTHONPATH=/code/app
    # command: sleep infinity
    # comment this because use .devcontainer for dev
    command: ["/code/.venv/bin/uvicorn", "app.main:app", "--host",  "0.0.0.0", "--port", "8000", "--reload-dir", "/code/app"]
    volumes:
      - ./app:/code/app
    restart: unless-stopped
    networks:
      - auth-network
    depends_on:
      db:
        condition: service_healthy

  db:
    image: postgres:17.4
    volumes:
      - auth_postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=auth_db
    ports:
      - "8124:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
    restart: unless-stopped
    networks:
      - auth-network

networks:
  auth-network:
    driver: bridge

volumes:
  auth_postgres_data:
